project_id = "qkjufptrgneockakeoth"

[functions.send-contact-email]
verify_jwt = false

[functions.create-retell-agent]
verify_jwt = false

[functions.fetch-retell-calls]
verify_jwt = false

[functions.retell-webhook]
verify_jwt = false

[functions.save-customer-info]
verify_jwt = false

[functions.create-web-call]
verify_jwt = false

[functions.grocery-search]
verify_jwt = false

[functions.initiate-outbound-call]
verify_jwt = false

[functions.fetch-airtable-leads]
verify_jwt = false

[functions.outbound-pre-call]
verify_jwt = false

[functions.outbound-post-call]
verify_jwt = false

[functions.fix-existing-outbound-flow]
verify_jwt = false

[functions.fetch-outbound-call-results]
verify_jwt = false

[functions.fetch-outbound-calls]
verify_jwt = false

[functions.update-outbound-agent]
verify_jwt = false

[functions.sync-agent-flow]
verify_jwt = false
